import { pixelItemAssets } from './pixel-item-art';

export const progressionItemAssets = [
  ...pixelItemAssets('gold-pickaxe', '金镐', 'pickaxe', 'gold'),
  ...pixelItemAssets('diamond-pickaxe', '钻石镐', 'pickaxe', 'diamond'),
  ...pixelItemAssets('stone-axe', '石斧', 'axe', 'stone'),
  ...pixelItemAssets('iron-axe', '铁斧', 'axe', 'iron'),
  ...pixelItemAssets('gold-axe', '金斧', 'axe', 'gold'),
  ...pixelItemAssets('diamond-axe', '钻石斧', 'axe', 'diamond'),
  ...pixelItemAssets('stone-sword', '石剑', 'sword', 'stone'),
  ...pixelItemAssets('iron-sword', '铁剑', 'sword', 'iron'),
  ...pixelItemAssets('gold-sword', '金剑', 'sword', 'gold'),
  ...pixelItemAssets('diamond-sword', '钻石剑', 'sword', 'diamond'),
  ...pixelItemAssets('wood-shovel', '木锹', 'shovel'),
  ...pixelItemAssets('stone-shovel', '石锹', 'shovel', 'stone'),
  ...pixelItemAssets('iron-shovel', '铁锹', 'shovel', 'iron'),
  ...pixelItemAssets('gold-shovel', '金锹', 'shovel', 'gold'),
  ...pixelItemAssets('diamond-shovel', '钻石锹', 'shovel', 'diamond'),
  ...pixelItemAssets('wood-hoe', '木锄', 'hoe'),
  ...pixelItemAssets('stone-hoe', '石锄', 'hoe', 'stone'),
  ...pixelItemAssets('iron-hoe', '铁锄', 'hoe', 'iron'),
  ...pixelItemAssets('gold-hoe', '金锄', 'hoe', 'gold'),
  ...pixelItemAssets('diamond-hoe', '钻石锄', 'hoe', 'diamond'),
  ...pixelItemAssets('gold-ingot', '金锭', 'gold-ingot'),
  ...pixelItemAssets('diamond', '钻石', 'diamond'),
  ...pixelItemAssets('stick', '木棍', 'stick'),
  ...pixelItemAssets('wood-pickaxe', '木镐', 'pickaxe'),
  ...pixelItemAssets('iron-pickaxe', '铁镐', 'pickaxe', 'iron'),
  ...pixelItemAssets('coal', '煤', 'coal'),
  ...pixelItemAssets('charcoal', '木炭', 'coal'),
  ...pixelItemAssets('iron-ingot', '铁锭', 'iron-ingot'),
  ...pixelItemAssets('apple', '苹果', 'apple'),
  ...pixelItemAssets('bread', '面包', 'bread'),
  ...pixelItemAssets('raw-porkchop', '生猪排', 'raw-porkchop'),
  ...pixelItemAssets('cooked-porkchop', '熟猪排', 'cooked-porkchop'),
  ...pixelItemAssets('raw-fish', '生鱼', 'raw-fish'),
  ...pixelItemAssets('cooked-fish', '熟鱼', 'cooked-fish'),
  ...pixelItemAssets('wheat', '小麦', 'wheat'),
];
