import { pixelItemAssets } from './pixel-item-art';
import { dyeItemAssets } from './dye-item-assets';

export const progressionItemAssets = [
  ...dyeItemAssets,
  ...pixelItemAssets('gold-pickaxe', '金镐', 'pickaxe', 'gold'),
  ...pixelItemAssets('diamond-pickaxe', '钻石镐', 'pickaxe', 'diamond'),
  ...pixelItemAssets('stone-axe', '石斧', 'axe', 'stone'),
  ...pixelItemAssets('iron-axe', '铁斧', 'axe', 'iron'),
  ...pixelItemAssets('gold-axe', '金斧', 'axe', 'gold'),
  ...pixelItemAssets('diamond-axe', '钻石斧', 'axe', 'diamond'),
  ...pixelItemAssets('stone-sword', '石剑', 'sword', 'stone'),
  ...pixelItemAssets('iron-sword', '铁剑', 'sword', 'iron'),
  ...pixelItemAssets('gold-sword', '金剑', 'sword', 'gold'),
  ...pixelItemAssets('diamond-sword', '钻石剑', 'sword', 'diamond'),
  ...pixelItemAssets('wood-shovel', '木锹', 'shovel'),
  ...pixelItemAssets('stone-shovel', '石锹', 'shovel', 'stone'),
  ...pixelItemAssets('iron-shovel', '铁锹', 'shovel', 'iron'),
  ...pixelItemAssets('gold-shovel', '金锹', 'shovel', 'gold'),
  ...pixelItemAssets('diamond-shovel', '钻石锹', 'shovel', 'diamond'),
  ...pixelItemAssets('wood-hoe', '木锄', 'hoe'),
  ...pixelItemAssets('stone-hoe', '石锄', 'hoe', 'stone'),
  ...pixelItemAssets('iron-hoe', '铁锄', 'hoe', 'iron'),
  ...pixelItemAssets('gold-hoe', '金锄', 'hoe', 'gold'),
  ...pixelItemAssets('diamond-hoe', '钻石锄', 'hoe', 'diamond'),
  ...pixelItemAssets('gold-ingot', '金锭', 'gold-ingot'),
  ...pixelItemAssets('diamond', '钻石', 'diamond'),
  ...pixelItemAssets('stick', '木棍', 'stick'),
  ...pixelItemAssets('wood-pickaxe', '木镐', 'pickaxe'),
  ...pixelItemAssets('iron-pickaxe', '铁镐', 'pickaxe', 'iron'),
  ...pixelItemAssets('coal', '煤', 'coal'),
  ...pixelItemAssets('charcoal', '木炭', 'coal'),
  ...pixelItemAssets('iron-ingot', '铁锭', 'iron-ingot'),
  ...pixelItemAssets('apple', '苹果', 'apple'),
  ...pixelItemAssets('bread', '面包', 'bread'),
  ...pixelItemAssets('raw-porkchop', '生猪排', 'raw-porkchop'),
  ...pixelItemAssets('cooked-porkchop', '熟猪排', 'cooked-porkchop'),
  ...pixelItemAssets('raw-fish', '生鱼', 'raw-fish'),
  ...pixelItemAssets('cooked-fish', '熟鱼', 'cooked-fish'),
  ...pixelItemAssets('wheat', '小麦', 'wheat'),
  ...pixelItemAssets('wheat-seeds', '小麦种子', 'wheat-seeds'),
  ...pixelItemAssets('leather', '皮革', 'raw-porkchop'),
  ...pixelItemAssets('bowl', '碗', 'bowl'),
  ...pixelItemAssets('bucket', '桶', 'bucket'),
  ...pixelItemAssets('water-bucket', '水桶', 'bucket'),
  ...pixelItemAssets('shears', '剪刀', 'shears'),
  ...pixelItemAssets('minecart', '矿车', 'minecart'),
  ...pixelItemAssets('chest-minecart', '运输矿车', 'chest-minecart'),
  ...pixelItemAssets('furnace-minecart', '动力矿车', 'furnace-minecart'),
  ...pixelItemAssets('boat', '船', 'boat'),
  ...pixelItemAssets('bow', '弓', 'bow'),
  ...pixelItemAssets('arrow', '箭', 'arrow'),
  ...pixelItemAssets('string', '线', 'string'),
  ...pixelItemAssets('feather', '羽毛', 'feather'),
  ...pixelItemAssets('flint', '燧石', 'flint'),
  ...pixelItemAssets('wool', '羊毛', 'wool'),
  ...pixelItemAssets('ink-sac', '墨囊', 'ink-sac'),
  ...pixelItemAssets('rotten-flesh', '腐肉', 'rotten-flesh'),
  ...pixelItemAssets('bone', '骨头', 'bone'),
  ...pixelItemAssets('gunpowder', '火药', 'gunpowder'),
  ...pixelItemAssets('slimeball', '黏液球', 'slimeball'),
  ...pixelItemAssets('bed', '床', 'bed'),
  ...pixelItemAssets('saddle', '鞍', 'saddle'),
  ...pixelItemAssets('lava-bucket', '熔岩桶', 'bucket'),
  ...(['leather', 'iron', 'gold', 'diamond'] as const).flatMap((tier) => {
    const material = tier === 'leather' ? 'wood' : tier;
    const label: Record<string, string> = { leather: '皮革', iron: '铁', gold: '金', diamond: '钻石' };
    return [
      ...pixelItemAssets(`${tier}-helmet`, `${label[tier]}头盔`, 'armor-helmet', material),
      ...pixelItemAssets(`${tier}-chestplate`, `${label[tier]}胸甲`, 'armor-chestplate', material),
      ...pixelItemAssets(`${tier}-leggings`, `${label[tier]}护腿`, 'armor-leggings', material),
      ...pixelItemAssets(`${tier}-boots`, `${label[tier]}靴子`, 'armor-boots', material),
    ];
  }),
];
