import { expect, test } from '@playwright/test';

test('统一目录、三类预览、像素编辑、保存刷新与包往返', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('dialog', (dialog) => dialog.accept());
  await page.goto('asset-workbench.html');
  await expect(page.getByRole('status', { name: '保存状态' })).toContainText('已就绪');
  await expect(page.locator('.asset-row')).toHaveCount(10);
  await expect(page.locator('.viewport')).toHaveAttribute('data-ready', 'true');
  await page.screenshot({ path: testInfo.outputPath('workbench-overview.png'), fullPage: true });
  await page.getByRole('button', { name: '灯笼 内置程序化模型', exact: true }).click();
  await expect(page.locator('.viewport')).toHaveAttribute('data-type', 'builtin-item-model');
  await expect(page.locator('.viewport')).toHaveAttribute('data-ready', 'true');
  await page.getByRole('button', { name: '图标 / 贴图', exact: true }).click();
  await expect(page.locator('.viewport')).toHaveAttribute('data-type', 'image-texture');
  await expect(page.locator('.viewport')).toHaveAttribute('data-ready', 'true');
  await expect(page.locator('.image-stage img')).toBeVisible();
  await page.getByLabel('采样对照').selectOption('linear');
  await page.getByLabel('平铺倍率').selectOption('4');
  await expect(page.locator('.viewport')).toHaveAttribute('data-ready', 'true');
  await page.screenshot({ path: testInfo.outputPath('image-adapter.png'), fullPage: true });
  await page.getByRole('button', { name: '石镐 像素挤出模型', exact: true }).click();
  await page.getByRole('button', { name: '复制为草稿', exact: true }).click();
  await expect(page.getByLabel('资产名称')).toBeEnabled();
  await page.getByLabel('资产名称').fill('青铜试作镐');
  await page.getByLabel('资产名称').press('Tab');
  await page.getByRole('button', { name: '颜色 2', exact: true }).click();
  const canvas = page.getByLabel('像素画布，方向键移动，空格绘制');
  const box = (await canvas.boundingBox())!;
  await page.mouse.click(box.x + box.width * 0.1, box.y + box.height * 0.1);
  await expect(page.getByRole('button', { name: '撤销', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  await page.getByRole('button', { name: '重做', exact: true }).click();
  await page.getByLabel('模型厚度').focus();
  await page.keyboard.press('Home');
  await page.keyboard.press('ArrowRight');
  await page.keyboard.press('ArrowRight');
  await page.getByLabel('握持点 X').fill('8');
  await page.getByLabel('握持点 X').press('Tab');
  await page.getByRole('button', { name: '保存修改', exact: true }).click();
  await expect(page.getByRole('status', { name: '保存状态' })).toContainText('已保存');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出资产包', exact: true }).click();
  const exported = await download;
  await exported.saveAs(testInfo.outputPath('asset.json'));
  await page.reload();
  await expect(page.getByRole('status', { name: '保存状态' })).toContainText('已就绪');
  await page.getByRole('button', { name: '按资产', exact: true }).click();
  await page.getByRole('button', { name: '青铜试作镐 草稿 · 像素挤出模型', exact: true }).click();
  await expect(page.getByLabel('模型厚度')).toHaveValue('3');
  await expect(page.getByLabel('握持点 X')).toHaveValue('8');
  await page.locator('input[type=file]').setInputFiles(testInfo.outputPath('asset.json'));
  await expect(page.getByRole('status', { name: '保存状态' })).toContainText('导入 2 项');
  await page.getByLabel('预览模式').selectOption('held');
  await expect(page.locator('.viewport')).toHaveAttribute('data-ready', 'true');
  await page.getByRole('button', { name: '挥动', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('held-early.png'), fullPage: true });
  await page.waitForTimeout(100);
  await page.screenshot({ path: testInfo.outputPath('held-middle.png'), fullPage: true });
  await page.getByRole('button', { name: '连续采集', exact: true }).click();
  await page.waitForTimeout(120);
  await page.getByRole('button', { name: '停止收手', exact: true }).click();
  await page.waitForTimeout(200);
  await page.screenshot({ path: testInfo.outputPath('held-rest.png'), fullPage: true });
  await page.setViewportSize({ width: 700, height: 900 });
  await page.getByRole('button', { name: '预览', exact: true }).click();
  await expect(page.getByLabel('预览模式')).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('workbench-700.png'), fullPage: true });
  expect(await page.evaluate(() => document.pointerLockElement)).toBeNull();
  expect(
    await page.evaluate(() => performance.getEntriesByType('resource').filter((r) => /worker.*\.ts/.test(r.name))),
  ).toEqual([]);
  expect(errors).toEqual([]);
});
