import type { ActorProfileInput, StarterEcologyConfigurationInput } from '@seedlands/stdlib/mod-api';

export const overworldActorProfiles: readonly ActorProfileInput[] = [
  {
    archetype: 'grazer',
    entityType: 'creature',
    maxHealth: 12,
    navigation: { speed: 1.6, perceptionRange: 10 },
    deathDrop: { itemId: 'berry', count: 2 },
  },
  {
    archetype: 'night-stalker',
    entityType: 'creature',
    maxHealth: 16,
    navigation: { speed: 2.2, perceptionRange: 12 },
    meleeDefinitionId: 'night-stalker-claw',
    deathDrop: { itemId: 'stone-block', count: 1 },
  },
  {
    archetype: 'settler',
    entityType: 'npc',
    maxHealth: 20,
    navigation: { speed: 1.4, perceptionRange: 10 },
    meleeDefinitionId: 'unarmed',
  },
  {
    archetype: 'chicken',
    entityType: 'creature',
    maxHealth: 4,
    navigation: { speed: 1.8, perceptionRange: 8 },
    disposition: 'passive',
    spawnWeight: 10,
    spawnBiomes: ['plains', 'forest'],
    deathDrop: { itemId: 'feather', count: 1 },
  },
  {
    archetype: 'cow',
    entityType: 'creature',
    maxHealth: 10,
    navigation: { speed: 2, perceptionRange: 10 },
    disposition: 'passive',
    spawnWeight: 8,
    spawnBiomes: ['plains', 'forest'],
    deathDrop: { itemId: 'leather', count: 1 },
  },
  {
    archetype: 'pig',
    entityType: 'creature',
    maxHealth: 10,
    navigation: { speed: 2, perceptionRange: 10 },
    disposition: 'passive',
    spawnWeight: 10,
    spawnBiomes: ['plains', 'forest', 'wet'],
    deathDrop: { itemId: 'raw-porkchop', count: 1 },
  },
  {
    archetype: 'pig-zombie',
    entityType: 'creature',
    maxHealth: 20,
    navigation: { speed: 2.3, perceptionRange: 12 },
    disposition: 'neutral',
    meleeDefinitionId: 'zombie-claw',
    deathDrop: { itemId: 'gold-ingot', count: 1 },
  },
  {
    archetype: 'sheep',
    entityType: 'creature',
    maxHealth: 8,
    navigation: { speed: 2, perceptionRange: 10 },
    disposition: 'passive',
    spawnWeight: 12,
    spawnBiomes: ['plains', 'forest', 'cold'],
    deathDrop: { itemId: 'wool', count: 1 },
  },
  {
    archetype: 'squid',
    entityType: 'creature',
    maxHealth: 10,
    navigation: { speed: 1.4, perceptionRange: 8 },
    disposition: 'passive',
    spawnWeight: 6,
    spawnBiomes: ['wet'],
    deathDrop: { itemId: 'ink-sac', count: 1 },
  },
  {
    archetype: 'wolf',
    entityType: 'creature',
    maxHealth: 8,
    navigation: { speed: 2.4, perceptionRange: 12 },
    disposition: 'neutral',
    spawnWeight: 4,
    spawnBiomes: ['forest', 'cold'],
  },
  {
    archetype: 'zombie',
    entityType: 'creature',
    maxHealth: 20,
    navigation: { speed: 2.3, perceptionRange: 12 },
    disposition: 'hostile',
    spawnWeight: 10,
    meleeDefinitionId: 'zombie-claw',
    deathDrop: { itemId: 'rotten-flesh', count: 1 },
  },
  {
    archetype: 'skeleton',
    entityType: 'creature',
    maxHealth: 20,
    navigation: { speed: 2.4, perceptionRange: 16 },
    disposition: 'hostile',
    spawnWeight: 10,
    deathDrop: { itemId: 'bone', count: 1 },
  },
  {
    archetype: 'spider',
    entityType: 'creature',
    maxHealth: 16,
    navigation: { speed: 2.8, perceptionRange: 12 },
    disposition: 'hostile',
    spawnWeight: 10,
    meleeDefinitionId: 'spider-bite',
    deathDrop: { itemId: 'string', count: 1 },
  },
  {
    archetype: 'creeper',
    entityType: 'creature',
    maxHealth: 20,
    navigation: { speed: 2.3, perceptionRange: 12 },
    disposition: 'hostile',
    spawnWeight: 8,
    meleeDefinitionId: 'creeper-bump',
    deathDrop: { itemId: 'gunpowder', count: 1 },
  },
  {
    archetype: 'slime',
    entityType: 'creature',
    maxHealth: 16,
    navigation: { speed: 2, perceptionRange: 10 },
    disposition: 'hostile',
    spawnWeight: 3,
    spawnBiomes: ['wet'],
    meleeDefinitionId: 'slime-bump',
    deathDrop: { itemId: 'slimeball', count: 1 },
  },
];

export const overworldDefaultPlayerMeleeDefinitionId = 'unarmed';

export const overworldStarterEcology: StarterEcologyConfigurationInput = {
  version: 1,
  actors: [
    { slot: 'forager', idPrefix: 'starter-grazer', archetype: 'grazer', hunger: 65 },
    { slot: 'predator', idPrefix: 'starter-stalker', archetype: 'night-stalker' },
    { slot: 'resident', idPrefix: 'starter-settler', archetype: 'settler', hunger: 20 },
  ],
  initialItem: { itemId: 'berry', count: 1 },
};
