import type { ItemDefinitionInput } from '@seedlands/stdlib/mod-api';

/** Version 1 storage IDs and voxel palette preserve supported save inputs. */
export const overworldItems: readonly ItemDefinitionInput[] = [
  ...(
    [
      ['white', '白色'],
      ['orange', '橙色'],
      ['magenta', '品红色'],
      ['light-blue', '淡蓝色'],
      ['yellow', '黄色'],
      ['lime', '黄绿色'],
      ['pink', '粉红色'],
      ['gray', '灰色'],
      ['light-gray', '淡灰色'],
      ['cyan', '青色'],
      ['purple', '紫色'],
      ['blue', '蓝色'],
      ['brown', '棕色'],
      ['green', '绿色'],
      ['red', '红色'],
      ['black', '黑色'],
    ] as const
  ).map(([id, name]) => ({
    id: `${id}-dye`,
    name: `${name}染料`,
    itemType: 'resource' as const,
    stackLimit: 64,
    capabilities: [],
  })),
  {
    id: 'glowstone-block',
    name: '辉光石',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 9 }],
  },
  {
    id: 'lantern',
    name: '灯笼',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 10 }],
  },
  {
    id: 'dirt-block',
    name: '泥土块',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 2 }],
  },
  {
    id: 'stone-block',
    name: '石块',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 3 }],
  },
  {
    id: 'wood-block',
    name: '原木',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 4 }],
  },
  {
    id: 'sand-block',
    name: '沙块',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 6 }],
  },
  {
    id: 'berry',
    name: '浆果',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 4, hungerRestore: 4 }],
  },
  {
    id: 'apple',
    name: '苹果',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 4, hungerRestore: 4 }],
  },
  {
    id: 'bread',
    name: '面包',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 5, hungerRestore: 5 }],
  },
  {
    id: 'raw-porkchop',
    name: '生猪排',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 3, hungerRestore: 3 }],
  },
  {
    id: 'cooked-porkchop',
    name: '熟猪排',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 8, hungerRestore: 8 }],
  },
  {
    id: 'raw-fish',
    name: '生鱼',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 2, hungerRestore: 2 }],
  },
  {
    id: 'cooked-fish',
    name: '熟鱼',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 5, hungerRestore: 5 }],
  },
  { id: 'wheat', name: '小麦', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'wheat-seeds', name: '小麦种子', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'plank',
    name: '木板',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 16 }],
  },
  { id: 'cobblestone', name: '圆石', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 17 }] },
  { id: 'glass', name: '玻璃', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 18 }] },
  { id: 'gold-ore', name: '金矿石', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 19 }] },
  {
    id: 'diamond-ore',
    name: '钻石矿石',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 20 }],
  },
  { id: 'iron-block', name: '铁块', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 21 }] },
  { id: 'gold-block', name: '金块', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 22 }] },
  {
    id: 'diamond-block',
    name: '钻石块',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 23 }],
  },
  { id: 'gold-ingot', name: '金锭', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'diamond', name: '钻石', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'sandstone', name: '砂岩', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 24 }] },
  {
    id: 'stone-bricks',
    name: '石砖',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 25 }],
  },
  {
    id: 'gold-pickaxe',
    name: '金镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 1, multiplier: 12 }],
  },
  {
    id: 'diamond-pickaxe',
    name: '钻石镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 4, multiplier: 8 }],
  },
  {
    id: 'stone-axe',
    name: '石斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 2, multiplier: 4 }],
  },
  {
    id: 'iron-axe',
    name: '铁斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 3, multiplier: 6 }],
  },
  {
    id: 'gold-axe',
    name: '金斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 1, multiplier: 12 }],
  },
  {
    id: 'diamond-axe',
    name: '钻石斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 4, multiplier: 8 }],
  },
  {
    id: 'stone-sword',
    name: '石剑',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'melee', definitionId: 'stone-sword' }],
  },
  {
    id: 'iron-sword',
    name: '铁剑',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'melee', definitionId: 'iron-sword' }],
  },
  {
    id: 'gold-sword',
    name: '金剑',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'melee', definitionId: 'gold-sword' }],
  },
  {
    id: 'diamond-sword',
    name: '钻石剑',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'melee', definitionId: 'diamond-sword' }],
  },
  {
    id: 'wood-shovel',
    name: '木锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 60 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 1, multiplier: 2 }],
  },
  {
    id: 'stone-shovel',
    name: '石锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 2, multiplier: 4 }],
  },
  {
    id: 'iron-shovel',
    name: '铁锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 3, multiplier: 6 }],
  },
  {
    id: 'gold-shovel',
    name: '金锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 1, multiplier: 12 }],
  },
  {
    id: 'diamond-shovel',
    name: '钻石锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 4, multiplier: 8 }],
  },
  {
    id: 'wood-hoe',
    name: '木锄',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 60 },
    capabilities: [{ type: 'till' }],
  },
  {
    id: 'stone-hoe',
    name: '石锄',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'till' }],
  },
  {
    id: 'iron-hoe',
    name: '铁锄',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'till' }],
  },
  {
    id: 'gold-hoe',
    name: '金锄',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'till' }],
  },
  {
    id: 'diamond-hoe',
    name: '钻石锄',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'till' }],
  },
  { id: 'charcoal', name: '木炭', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'stick', name: '木棍', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'wood-axe',
    name: '木斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 60 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 1, multiplier: 3 }],
  },
  {
    id: 'stone-pickaxe',
    name: '石镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 2, multiplier: 4 }],
  },
  {
    id: 'wood-sword',
    name: '木剑',
    itemType: 'tool',
    stackLimit: 1,
    capabilities: [{ type: 'melee', definitionId: 'wood-sword' }],
  },

  { id: 'workbench', name: '工作台', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 11 }] },
  { id: 'chest', name: '箱子', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 12 }] },
  { id: 'furnace', name: '炉体', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 13 }] },
  { id: 'coal', name: '煤', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'raw-iron', name: '铁矿石', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 15 }] },
  { id: 'iron-ingot', name: '铁锭', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'wood-pickaxe',
    name: '木镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 60 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 1, multiplier: 2 }],
  },
  {
    id: 'iron-pickaxe',
    name: '铁镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 3, multiplier: 6 }],
  },
  { id: 'leather', name: '皮革', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'bowl', name: '碗', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'bucket',
    name: '桶',
    itemType: 'resource',
    stackLimit: 16,
    capabilities: [{ type: 'fluid-container', fluid: 'empty' }],
  },
  {
    id: 'water-bucket',
    name: '水桶',
    itemType: 'resource',
    stackLimit: 1,
    capabilities: [{ type: 'fluid-container', fluid: 'water' }],
  },
  { id: 'shears', name: '剪刀', itemType: 'tool', stackLimit: 1, durability: { max: 238 }, capabilities: [] },
  { id: 'minecart', name: '矿车', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'chest-minecart', name: '运输矿车', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'furnace-minecart', name: '动力矿车', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'boat', name: '船', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'string', name: '线', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'feather', name: '羽毛', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'flint', name: '燧石', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'wool', name: '羊毛', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'ink-sac', name: '墨囊', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'rotten-flesh', name: '腐肉', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'bone', name: '骨头', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'gunpowder', name: '火药', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'slimeball', name: '黏液球', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'bed', name: '床', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'saddle', name: '鞍', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'milk-bucket', name: '奶桶', itemType: 'food', stackLimit: 1, capabilities: [] },
  { id: 'egg', name: '鸡蛋', itemType: 'resource', stackLimit: 16, capabilities: [] },
  { id: 'fishing-rod', name: '钓鱼竿', itemType: 'tool', stackLimit: 1, durability: { max: 65 }, capabilities: [] },
  {
    id: 'lava-bucket',
    name: '熔岩桶',
    itemType: 'resource',
    stackLimit: 1,
    capabilities: [{ type: 'fluid-container', fluid: 'lava' }],
  },
  { id: 'obsidian', name: '黑曜石', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 28 }] },
  { id: 'tnt', name: 'TNT', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 30 }] },
  { id: 'sapling', name: '树苗', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 31 }] },
  { id: 'flower', name: '花', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 33 }] },
  { id: 'mushroom', name: '蘑菇', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 34 }] },
  { id: 'sugar-cane', name: '甘蔗', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 35 }] },
  { id: 'cactus', name: '仙人掌', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 36 }] },
  { id: 'arrow', name: '箭', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'bow',
    name: '弓',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 384 },
    capabilities: [{ type: 'ranged', ammunitionItemId: 'arrow', damage: 4, speed: 16, lifetimeSeconds: 5 }],
  },
  ...(
    [
      ['leather', '皮革', 'leather', 55, { helmet: 1, chestplate: 3, leggings: 2, boots: 1 }],
      ['iron', '铁', 'iron-ingot', 165, { helmet: 2, chestplate: 6, leggings: 5, boots: 2 }],
      ['gold', '金', 'gold-ingot', 77, { helmet: 2, chestplate: 5, leggings: 3, boots: 1 }],
      ['diamond', '钻石', 'diamond', 363, { helmet: 3, chestplate: 8, leggings: 6, boots: 3 }],
    ] as const
  ).flatMap(([tier, tierName, , durability, points]) =>
    (
      [
        ['helmet', '头盔'],
        ['chestplate', '胸甲'],
        ['leggings', '护腿'],
        ['boots', '靴子'],
      ] as const
    ).map(([slot, slotName]) => ({
      id: `${tier}-${slot}`,
      name: `${tierName}${slotName}`,
      itemType: 'armor' as const,
      stackLimit: 1,
      durability: { max: durability },
      capabilities: [{ type: 'armor' as const, slot, points: points[slot] }],
    })),
  ),
];
