import type { ItemDefinitionInput } from '@seedlands/stdlib/mod-api';

/** Version 1 storage IDs and voxel palette preserve supported save inputs. */
export const overworldItems: readonly ItemDefinitionInput[] = [
  {
    id: 'glowstone-block',
    name: '辉光石',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 9 }],
  },
  {
    id: 'lantern',
    name: '灯笼',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 10 }],
  },
  {
    id: 'dirt-block',
    name: '泥土块',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 2 }],
  },
  {
    id: 'stone-block',
    name: '石块',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 3 }],
  },
  {
    id: 'wood-block',
    name: '原木',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 4 }],
  },
  {
    id: 'sand-block',
    name: '沙块',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 6 }],
  },
  {
    id: 'berry',
    name: '浆果',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 4, hungerRestore: 4 }],
  },
  {
    id: 'plank',
    name: '木板',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 16 }],
  },
  { id: 'cobblestone', name: '圆石', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 17 }] },
  { id: 'glass', name: '玻璃', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 18 }] },
  { id: 'gold-ore', name: '金矿石', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 19 }] },
  {
    id: 'diamond-ore',
    name: '钻石矿石',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 20 }],
  },
  { id: 'iron-block', name: '铁块', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 21 }] },
  { id: 'gold-block', name: '金块', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 22 }] },
  {
    id: 'diamond-block',
    name: '钻石块',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 23 }],
  },
  { id: 'gold-ingot', name: '金锭', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'diamond', name: '钻石', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'sandstone', name: '砂岩', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 24 }] },
  {
    id: 'stone-bricks',
    name: '石砖',
    itemType: 'block',
    stackLimit: 64,
    capabilities: [{ type: 'place', voxel: 25 }],
  },
  {
    id: 'gold-pickaxe',
    name: '金镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 1, multiplier: 12 }],
  },
  {
    id: 'diamond-pickaxe',
    name: '钻石镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 4, multiplier: 8 }],
  },
  {
    id: 'stone-axe',
    name: '石斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 2, multiplier: 4 }],
  },
  {
    id: 'iron-axe',
    name: '铁斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 3, multiplier: 6 }],
  },
  {
    id: 'gold-axe',
    name: '金斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 1, multiplier: 12 }],
  },
  {
    id: 'diamond-axe',
    name: '钻石斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 4, multiplier: 8 }],
  },
  {
    id: 'stone-sword',
    name: '石剑',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'melee', definitionId: 'stone-sword' }],
  },
  {
    id: 'iron-sword',
    name: '铁剑',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'melee', definitionId: 'iron-sword' }],
  },
  {
    id: 'gold-sword',
    name: '金剑',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'melee', definitionId: 'gold-sword' }],
  },
  {
    id: 'diamond-sword',
    name: '钻石剑',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'melee', definitionId: 'diamond-sword' }],
  },
  {
    id: 'wood-shovel',
    name: '木锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 60 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 1, multiplier: 2 }],
  },
  {
    id: 'stone-shovel',
    name: '石锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 2, multiplier: 4 }],
  },
  {
    id: 'iron-shovel',
    name: '铁锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 3, multiplier: 6 }],
  },
  {
    id: 'gold-shovel',
    name: '金锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 32 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 1, multiplier: 12 }],
  },
  {
    id: 'diamond-shovel',
    name: '钻石锹',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 1561 },
    capabilities: [{ type: 'mine', tool: 'shovel', tier: 4, multiplier: 8 }],
  },
  { id: 'charcoal', name: '木炭', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'stick', name: '木棍', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'wood-axe',
    name: '木斧',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 60 },
    capabilities: [{ type: 'mine', tool: 'axe', tier: 1, multiplier: 3 }],
  },
  {
    id: 'stone-pickaxe',
    name: '石镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 132 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 2, multiplier: 4 }],
  },
  {
    id: 'wood-sword',
    name: '木剑',
    itemType: 'tool',
    stackLimit: 1,
    capabilities: [{ type: 'melee', definitionId: 'wood-sword' }],
  },

  { id: 'workbench', name: '工作台', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 11 }] },
  { id: 'chest', name: '箱子', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 12 }] },
  { id: 'furnace', name: '炉体', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 13 }] },
  { id: 'coal', name: '煤', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'raw-iron', name: '铁矿石', itemType: 'block', stackLimit: 64, capabilities: [{ type: 'place', voxel: 15 }] },
  { id: 'iron-ingot', name: '铁锭', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'wood-pickaxe',
    name: '木镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 60 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 1, multiplier: 2 }],
  },
  {
    id: 'iron-pickaxe',
    name: '铁镐',
    itemType: 'tool',
    stackLimit: 1,
    durability: { max: 250 },
    capabilities: [{ type: 'mine', tool: 'pickaxe', tier: 3, multiplier: 6 }],
  },
];
