import type { ItemDefinitionInput } from '@seedlands/stdlib/mod-api';

export const portableItems: readonly ItemDefinitionInput[] = [
  { id: 'paper', name: '纸', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'redstone-dust', name: '红石粉', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'compass', name: '指南针', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'clock', name: '时钟', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'map', name: '地图', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'flint-and-steel', name: '打火石', itemType: 'tool', stackLimit: 1, durability: { max: 65 }, capabilities: [] },
  {
    id: 'mushroom-stew',
    name: '蘑菇煲',
    itemType: 'food',
    stackLimit: 1,
    capabilities: [{ type: 'consume', healthRestore: 5, hungerRestore: 5 }],
  },
  { id: 'painting', name: '画', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'golden-apple',
    name: '金苹果',
    itemType: 'food',
    stackLimit: 1,
    capabilities: [{ type: 'consume', healthRestore: 10, hungerRestore: 10 }],
  },
  { id: 'sign', name: '告示牌', itemType: 'block', stackLimit: 16, capabilities: [{ type: 'place', voxel: 56 }] },
  { id: 'wooden-door', name: '木门', itemType: 'block', stackLimit: 64, capabilities: [] },
  { id: 'snowball', name: '雪球', itemType: 'resource', stackLimit: 16, capabilities: [] },
  { id: 'brick', name: '红砖', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'clay', name: '黏土', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'book', name: '书', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'sugar', name: '糖', itemType: 'resource', stackLimit: 64, capabilities: [] },
  {
    id: 'cake',
    name: '蛋糕',
    itemType: 'block',
    stackLimit: 1,
    capabilities: [{ type: 'place', voxel: 58 }],
  },
  {
    id: 'cookie',
    name: '曲奇',
    itemType: 'food',
    stackLimit: 64,
    capabilities: [{ type: 'consume', healthRestore: 1, hungerRestore: 1 }],
  },
  { id: 'cocoa-beans', name: '可可豆', itemType: 'resource', stackLimit: 64, capabilities: [] },
  { id: 'record-13', name: '唱片 13', itemType: 'resource', stackLimit: 1, capabilities: [] },
  { id: 'record-cat', name: '唱片 Cat', itemType: 'resource', stackLimit: 1, capabilities: [] },
];
